Repository zer0Kerbal/Halloween, pull requests merged in 2022-10, with the labels that each got.

#45 ✨ New norwegian translation
  GameData/Halloween/Localization/no-no.cfg
Labels: type: localization, state: approved, hacktoberfest-accepted

#46 New img
  readme.md
Labels: issue: documentation, issue: image, hacktoberfest-accepted

#50 Version 1.0.0.1-release `<Ungoliant Edderkopp Emporium>` edition
  GameData/Halloween/1.0.0.1.htm
  GameData/Halloween/Attributions.htm
  GameData/Halloween/Halloween.version
  GameData/Halloween/Localization/en-us.cfg
  GameData/Halloween/Localization/no-no.cfg
  GameData/Halloween/changelog.md
  GameData/Halloween/readme.htm
  Halloween.version
  changelog.md
  docs/Attributions.md
  docs/Localizations.md
  docs/changelog.md
  img/HeroLogo_1920x1920-OLD.jpg
  img/HeroLogo_1920x1920-OLD.png
  img/HeroLogo_1920x1920.jpg
  img/HeroLogo_1920x1920.png
  img/nli2work.gif
  json/mod.json
  readme.md
Labels: semantic: release

#55 Version 1.0.0.2-release `<Caerfinon's Contract>` edition
  GameData/Halloween/1.0.0.2.htm
  GameData/Halloween/Agencies/Agents.cfg
  GameData/Halloween/Agencies/jollykerbaljib_scaled.truecolor
  GameData/Halloween/Attributions.htm
  GameData/Halloween/Contracts/InterSidera/Contract.cfg
  GameData/Halloween/Contracts/InterSidera/Flags/intersidera.dds
  GameData/Halloween/Contracts/InterSidera/intersidera_scaled.dds
  GameData/Halloween/Halloween.version
  GameData/Halloween/Localization/en-us.cfg
  GameData/Halloween/Localization/no-no.cfg
  GameData/Halloween/changelog.md
  Halloween.version
  changelog.md
  docs/Attributions.md
  docs/changelog.md
  json/mod.json
Labels: semantic: release
